spring.application.name=ai_resume
spring.datasource.url=jdbc:mysql://localhost:3306/ai_resume?serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=
file.upload.dir=
api.key=
api.url=
spring.data.redis.host=localhost
spring.data.redis.port=6379
resume.task.delay=1000
